name: Platformer Generated config-manage-dev-main-push Build
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: ghcr.io/eclk/configuration-management
      CONTAINER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/heads/}-${{github.sha}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD_E8EBD09C_D45F_4ABC_91AC_4DCC9B515FCF }}
      - name: Build the Docker image
        run: docker build --tag ${SERVICE_NAME}:${{steps.event-version.outputs.SOURCE_TAG }} --build-arg DB_HOST=${{secrets.DEV_DB_HOST}} --build-arg DB_USER=${{secrets.DEV_DB_USER}} --build-arg DB_PASSWORD=${{secrets.DEV_DB_PASSWORD}} --build-arg DB_NAME=${{secrets.DEV_DB_NAME}} --build-arg DB_DIALECT=${{secrets.DEV_DB_DIALECT}} --file Dockerfile .
      - name: GitHub Image Push
        run: docker push $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_521B7B83_DB8E_4706_BAD6_C12A1ED8B42B}}
          project-id: ${{secrets.PROJECT_ID_521B7B83_DB8E_4706_BAD6_C12A1ED8B42B}}
          token: ${{secrets.AUTOGENERATED_CICD_521B7B83_DB8E_4706_BAD6_C12A1ED8B42B}}
          image-name: ${{env.SERVICE_NAME}}
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: 1df93825-ea84-4d81-afe6-a89d51583d38
